### ISSUE TITLE
Milestones criadas e v0.1

### ISSUE THREAD

**Issue by josevictor022** [LotusAttic/fairytail-gandalf#3]
Pessoal, eu já fiz as milestones, estou com umas ideias aqui para a história e talvez hoje ainda eu mande um script base. Agora, para fazer a Wiki page a gente precisa dela pronta né? Quem vai fazer? Confesso que não sei mas se quiserem eu tento.

**Comment by gabrielduuarte** [comment]
Criei as labels urgent e late, estavam faltando.

**Comment by josevictor022** [comment]
Tenho uma duvida, o arquivo de organização não vai pro developer? fica só no master mesmo?

**Comment by gabrielduuarte** [comment]
Em relação a wiki, eu vou cria-la agora.

**Comment by josevictor022** [comment]
ok

**Comment by gabrielduuarte** [comment]
Eu acho que ela entra quando você der o merge do master no develop.

**Comment by gabrielduuarte** [comment]
Preciso criar um nome pra wiki, pensei em misturar o nome da historia com a palavra wiki, mas como n tem nome ainda, vou deixar GandWiki (gandalf com wiki ).

**Comment by josevictor022** [comment]
É que eu pensei que quando desse git pull ele pegava tudo que tava no master

**Comment by gabrielduuarte** [comment]
Quando você dá git pull no develop ele atualiza apenas o develop.

**Comment by gabrielduuarte** [comment]
Criei a wiki!!
